### ISSUE TITLE
Question about the new update

### ISSUE THREAD

**Issue by ParsapythonLv** [Emperor-One/Hamster-Key-Telegram-Bot#15]
The new update is really interesting and better 
but I have a question, which is better?
use free proxy or don't use proxy
In order to use the free proxy, we only need to set its variable to true?

**Comment by ParsapythonLv** [comment]
im using the proxy option but i getting this error
```
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 276, in run
    key = await completed_task
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/tasks.py", line 616, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44 | INFO     | 53 - Delay for 0 seconds
2024-09-06 14:14:44 | INFO     | 56 - Generating for client: Adedeji ðŸ¸ - Aded38: 6455484363
2024-09-06 14:14:44 | INFO     | 272 - Generating 4 keys for Twerk Race 3D
2024-09-06 14:14:44 | INFO     | 82 - Fetching Proxies id: a68faa32-edd6-4555-9352-8258279f38db
2024-09-06 14:14:44 | INFO     | 82 - Fetching Proxies id: 86a51867-e0ab-4c91-bf0f-9471c80b06ba
2024-09-06 14:14:44 | INFO     | 82 - Fetching Proxies id: 9737bebe-d367-4cb7-8cf1-879ed0415bab
2024-09-06 14:14:44 | INFO     | 82 - Fetching Proxies id: 4c36bb9e-f74e-4c56-8735-a43f2e1e02b3
2024-09-06 14:14:44,935 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-19' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,937 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-20' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,938 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-21' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,938 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-22' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,938 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-23' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,938 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-25' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,938 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-26' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,939 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-31' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,939 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-27' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,939 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-28' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,939 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-29' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,939 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-32' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,940 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-33' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,940 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-34' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-09-06 14:14:44,940 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-63' coro=<play_the_game() done, defined at /home/a1018745/Hamster-Key-Telegram-Bot/server.py:228> exception=JSONDecodeError('Expecting value: line 1 column 1 (char 0)')>
Traceback (most recent call last):
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 239, in play_the_game
    proxies = await get_proxies(client_id)
  File "/home/a1018745/Hamster-Key-Telegram-Bot/server.py", line 84, in get_proxies
    proxies_data = proxies_response.json()
  File "/home/a1018745/.local/lib/python3.8/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/opt/rh/rh-python38/root/usr/lib64/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/rh/rh-py

**Comment by Emperor-One** [comment]
> The new update is really interesting and better but I have a question, which is better? use free proxy or don't use proxy In order to use the free proxy, we only need to set its variable to true?

It's better to use proxies if a lot of people use your bot, but if only a few people are using your bot, it's better to do no proxies than to use free proxies because they can be slow.

**Comment by Emperor-One** [comment]
> im using the proxy option but i getting this error

Go to [line 83](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L83) in server.py, and underneath it, add the following statement:
```python
print(f"DEBUG: {response.content}")
```
And show me the output.

**Comment by ParsapythonLv** [comment]
> > The new update is really interesting and better but I have a question, which is better? use free proxy or don't use proxy In order to use the free proxy, we only need to set its variable to true?
> 
> It's better to use proxies if a lot of people use your bot, but if only a few people are using your bot, it's better to do no proxies than to use free proxies because they can be slow.

thanks bro , so better I don't use proxy because just 2 people using this bot

**Comment by ParsapythonLv** [comment]
> > im using the proxy option but i getting this error
> 
> Go to [line 83](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L83) in server.py, and underneath it, add the following statement:
> 
> ```python
> print(f"DEBUG: {proxies_response.content}")
> ```
> 
> And show me the output.

  File "server.py", line 84
    proxies_data = proxies_response.json()
                                                                        ^
IndentationError: unindent does not match any outer indentation level

**Comment by ParsapythonLv** [comment]
> > > im using the proxy option but i getting this error
> > 
> > 
> > Go to [line 83](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L83) in server.py, and underneath it, add the following statement:
> > ```python
> > print(f"DEBUG: {proxies_response.content}")
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > And show me the output.
> 
> File "server.py", line 84 proxies_data = 
```
proxies_response.json() 
                                         ^ 
IndentationError: unindent does not match any outer indentation level
```

**Comment by ParsapythonLv** [comment]
> > > > im using the proxy option but i getting this error
> > > 
> > > 
> > > Go to [line 83](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L83) in server.py, and underneath it, add the following statement:
> > > ```python
> > > print(f"DEBUG: {proxies_response.content}")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And show me the output.
> > 
> > 
> > File "server.py", line 84 proxies_data =
> 
> ```
  File "server.py", line 84
    proxies_data = proxies_response.json()
                                         ^
IndentationError: unindent does not match any outer indentation level
> ```

**Comment by ParsapythonLv** [comment]
> > > The new update is really interesting and better but I have a question, which is better? use free proxy or don't use proxy In order to use the free proxy, we only need to set its variable to true?
> > 
> > 
> > It's better to use proxies if a lot of people use your bot, but if only a few people are using your bot, it's better to do no proxies than to use free proxies because they can be slow.
> 
> thanks bro , so better I don't use proxy because just 2 people using this bot

bro 

> > im using the proxy option but i getting this error
> 
> Go to [line 83](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L83) in server.py, and underneath it, add the following statement:
> 
> ```python
> print(f"DEBUG: {proxies_response.content}")
> ```
> 
> And show me the output.

when i send a command in the bot to make a key this spamming error happening and don't stop
![Screenshot_2024-09-07-08-18-57-192_com sonelli juicessh](https://github.com/user-attachments/assets/d38f4932-498e-4750-90c5-9e6439cd0856)

![Screenshot_2024-09-07-08-18-55-141_com sonelli juicessh](https://github.com/user-attachments/assets/629f5061-5f83-4780-8325-b1850b2c91d3)

**Comment by ParsapythonLv** [comment]
> > > > im using the proxy option but i getting this error
> > > 
> > > 
> > > Go to [line 83](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L83) in server.py, and underneath it, add the following statement:
> > > ```python
> > > print(f"DEBUG: {proxies_response.content}")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And show me the output.
> > 
> > 
> > File "server.py", line 84 proxies_data =
> 
> ```
>   File "server.py", line 84
>     proxies_data = proxies_response.json()
>                                          ^
> IndentationError: unindent does not match any outer indentation level
> ```



> > im using the proxy option but i getting this error
> 
> Go to [line 83](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L83) in server.py, and underneath it, add the following statement:
> 
> ```python
> print(f"DEBUG: {proxies_response.content}")
> ```
> 
> And show me the output.

By nothing I meant:
![IMG_20240907_082718](https://github.com/user-attachments/assets/4729f8fe-ab54-429c-a7dd-3a3c94f73d32)

**Comment by Emperor-One** [comment]
> > > > im using the proxy option but i getting this error
> > > 
> > > 
> > > Go to [line 83](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/server.py#L83) in server.py, and underneath it, add the following statement:
> > > ```python
> > > print(f"DEBUG: {proxies_response.content}")
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > And show me the output.
> > 
> > 
> > File "server.py", line 84 proxies_data =
> 
> nothing printed maybe there is no respons from the scraproxy site + when run it normally without proxy that getting spam errors

You mean it says DEBUG: and then nothing? What about after that? It should give you something.

Here, try this just in case:
`pip install httpx[brotli]`

**Comment by Emperor-One** [comment]
> > > The new update is really interesting and better but I have a question, which is better? use free proxy or don't use proxy In order to use the free proxy, we only need to set its variable to true?
> > 
> > 
> > It's better to use proxies if a lot of people use your bot, but if only a few people are using your bot, it's better to do no proxies than to use free proxies because they can be slow.
> 
> thanks bro , so better I don't use proxy because just 2 people using this bot

As for this. Yeah don't bother bro. It's not worth messing with laggy, unreliable proxies if you are just two people. We are three people using this bot now, and it works flawlessly without proxies
