### ISSUE TITLE
How to fix it?

### ISSUE THREAD

**Issue by sfpghjgf** [Emperor-One/Hamster-Key-Telegram-Bot#5]
C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Scripts\python.exe C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\bot.py 
2024-08-24 18:57:22 | INFO     | 115 - Server is running. Awaiting users...
2024-08-24 18:57:27,230 - telegram.ext.Updater - ERROR - Error while getting Updates: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-08-24 18:57:27,231 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\ext\_updater.py", line 755, in _network_loop_retry
    if not await do_action():
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\ext\_updater.py", line 749, in do_action
    return action_cb_task.result()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\ext\_updater.py", line 389, in polling_action_cb
    raise exc
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\ext\_updater.py", line 378, in polling_action_cb
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 649, in get_updates
    updates = await super().get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\_bot.py", line 4364, in get_updates
    await self._post(
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\_bot.py", line 622, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\ext\_extbot.py", line 355, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\_bot.py", line 651, in _do_post
    result = await request.post(
             ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 200, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\1\PycharmProjects\Hamster-Key-Telegram-Bot\.venv\Lib\site-packages\telegram\request\_baserequest.py", line 383, in _request_wrapper
    raise Conflict(message)
telegram.error.Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running

How to fix it?

**Comment by Emperor-One** [comment]
This issue is caused by running more than one telegram bot instances. You have either ran the script multiple times or you have shared your token with someone else and that person is running your bot.

**Comment by Emperor-One** [comment]
This is why it is important to keep your token secure by at least putting it in an [environment variable](https://github.com/Emperor-One/Hamster-Key-Telegram-Bot/blob/main/README.md#environment-variables). To fix this you have to make sure only one bot.py is running.
